### ISSUE TITLE
How to install ctrlppcheck

### ISSUE THREAD

**Issue by Finist02** [LukasSchopp/vscode-ctrlpptools#2]
Good day, I can not install the ctrlppcheck. The installer is not downloaded on the official website. Also "Go to definition" in VS Code does not work

**Comment by LukasSchopp** [comment]
You don‘t see the Installer button as in the screenshot?

![F47ECC39-A27F-4DB8-971E-2420169A73BA](https://user-images.githubusercontent.com/29131325/144719988-4d040353-4b25-41fa-bfe5-481b5c705c91.png)

**Comment by Finist02** [comment]
Hello, i see, but when I click button, nothing happens

**Comment by Finist02** [comment]
Sorry, the problem has been resolved. Chrome blocked downloads, another browser helped

**Comment by LukasSchopp** [comment]
> Sorry, the problem has been resolved. Chrome blocked downloads, another browser helped

happy that it‘s working now. If you have any questions just ask. Also have a look to our YouTube channel: https://youtube.com/playlist?list=PL2d2ogK6sZLVkSdI1y6W6y6WtHAkLGiaY
