### ISSUE TITLE
SloopTools Installer

### ISSUE THREAD

**Issue by Finist02** [LukasSchopp/vscode-ctrlpptools#3]
Hi, I downloaded SloopTools Installer, but when I try download any demo product, download does not start
![image](https://user-images.githubusercontent.com/43680801/144749285-669d7c16-5cc2-4c69-9dc1-e10a0d68ffa2.png)
I see your vidoe in yotube chanel, there were no problems, but i have. Firewall and antivirus turned off.
I would be grateful if you can help!

**Comment by LukasSchopp** [comment]
Can you please go to settings on the installer (click on the name --> settings) and change the Log Level from currently INFO to ALL and click "Change" so the Current level si showing: ALL as you see in the screenshot.

![image](https://user-images.githubusercontent.com/29131325/144762532-8c27b9c7-6f4f-4084-87d5-2339af1de6ca.png)

Please try to download some of the addons.

After that please send me the log files from C:\ProgramData\SloopTools\logs via mail to info@slooptools.com

Sorry for the inconvenience.

Best wishes
Lukas

**Comment by Finist02** [comment]
Send logs on mail
